version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.back
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - db

  planner:
    build:
      context: .
      dockerfile: deployment/Dockerfile.planner
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.front
    restart: always
    ports:
      - 8081:80
    depends_on:
      - backend

  # gui:
  #   build:
  #     context: .
  #     dockerfile: deployment/Dockerfile.gui
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - backend

  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
    logging:
      driver: none
    depends_on:
      - db
    profiles:
      - debug
