version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.back
    restart: always
    ports:
      - "8080:8080"
    expose:
      - 8080

  frontend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.front
    restart: always
    ports:
      - 8081:80
    depends_on:
      - backend

  db:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
