FROM cirrusci/flutter as builder
WORKDIR /app
COPY gui .
RUN flutter build web --release

FROM nginx:1.21
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf
RUN rm -fr /usr/share/nginx/html
COPY --from=builder /app/build/web /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
