POST http://localhost:8080/api/register

{
    "name": "harry potter",
    "email": "harry.potter@hogwarts.uk",
    "password": "slytherin"
}

###

POST http://localhost:8080/api/login

{
    "email": "harry.potter@hogwarts.uk",
    "password": "slytherin"
}

###

GET http://localhost:8080/api/home

###

GET http://localhost:8080/api/team

###

GET http://localhost:8080/api/shop/players
